import Head from 'next/head'
import { authMiddleWare } from '../common/utils/middleWares'
import useAuth from '../modules/auth/hooks/useAuth'

function Home({ todos }: Props) {
  const { handleLogout } = useAuth()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>

      <main>
        <div>
          <button onClick={handleLogout}>logout</button>
        </div>
        {todos.map((todo) => (
          <div key={todo.id}>{todo.title}</div>
        ))}
      </main>
    </>
  )
}

export const getServerSideProps = authMiddleWare(async (_, isValid) => {
  if (!isValid) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    }
  }

  const data = await (
    await fetch('https://jsonplaceholder.typicode.com/todos')
  ).json()
  return { props: { todos: data } }
})

type Props = {
  todos: {
    id: number
    userId: number
    title: string
    completed: boolean
  }[]
}

export default Home
