import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { authMiddleWare } from '../utils/middleWares'
import useUser from '../hooks/useUser/useUser'

function Home({ todos }: Props) {
  const { logout } = useUser()

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <button onClick={logout}>logout</button>
        </div>
        {todos.map((todo) => (
          <div key={todo.id}>{todo.title}</div>
        ))}
      </main>
    </div>
  )
}

export const getServerSideProps = authMiddleWare(async (_, isValid) => {
  if (!isValid) {
    return {
      redirect: {
        destination: '/login',
        permanent: false,
      },
    }
  }

  const data = await (
    await fetch('https://jsonplaceholder.typicode.com/todos')
  ).json()
  return { props: { todos: data } }
})

type Props = {
  todos: {
    id: number
    userId: number
    title: string
    completed: boolean
  }[]
}

export default Home
